# Generated by Django 3.0.8 on 2020-07-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='cars_pics'),
        ),
    ]
