# Generated by Django 3.0.8 on 2020-08-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'Cars'},
        ),
    ]
