# Generated by Django 3.0.8 on 2020-08-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carstatus',
            options={'verbose_name_plural': 'Car statuses'},
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='car.CarStatus'),
        ),
    ]
