# Generated by Django 3.0.8 on 2020-08-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20200801_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='car.CarStatus'),
        ),
    ]
